[package]
name = "imasparql_details"
version = "0.1.0"
authors = ["jon"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
rocket_codegen = "0.4.4"
serde = "*"
serde_json = "*"
serde_derive = "*"
ureq = { version = "*", features = ["json"] }
url = "2.1.0"
percent-encoding = "2.1.0"